version: '3.8'
services:
  student-records:
    image: student-records-backend    
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  notification:
    image: notification-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  file-uploader:
    image: file-uploader-backend
    ports: 
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  file-processor:
    image: file-processor-backend
    ports: 
      - "4500:4500"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
